name: Test DevContainer

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dev Containers CLI
        run: npm install -g @devcontainers/cli

      - name: Test DevContainer
        run: |
          devcontainer build --workspace-folder .
          devcontainer up --workspace-folder .
